name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t imagewebapidemo:latest
      
    - name: Save image to tar
      run: docker save imagewebapidemo:latest -o imagewebapidemo.tar
      
    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: imagewebapidemo
        path: imagewebapidemo.tar
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image
      run: docker tag imagewebapidemo:latest moncompte/imagewebapidemo:latest && docker push moncompte/imagewebapidemo:latest
